### ISSUE TITLE
npm install emoji-regex  returns MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by kimpoy010** [mathiasbynens/emoji-regex#90]
I am getting an error while trying to install the package

```
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'emoji-regex'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\usernmae\AppData\Roaming\npm-cache\_logs\2021-07-04T08_51_10_141Z-debug.log
```

This is the full log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'emoji-regex',
1 verbose cli   '--save' ]
2 info using npm@6.13.4
3 info using node@v10.18.0
4 verbose stack Error: Cannot find module 'emoji-regex'
4 verbose stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:692:17)
4 verbose stack     at require (internal/modules/cjs/helpers.js:25:18)
4 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\cli-table3\node_modules\string-width\index.js:4:20)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:778:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:653:32)
4 verbose stack     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:692:17)
4 verbose stack     at require (internal/modules/cjs/helpers.js:25:18)
4 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\cli-table3\src\utils.js:2:21)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:778:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:653:32)
5 verbose cwd D:\Files and Projects\Projects\SakuraSmartHome\smarthome-local\app-start\functions
6 verbose Windows_NT 10.0.19043
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "emoji-regex" "--save"
8 verbose node v10.18.0
9 verbose npm  v6.13.4
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'emoji-regex'
12 verbose exit [ 1, true ]
```

**Comment by joshinihal** [comment]
Hey @kimpoy010 , where you able to find a solution for this? I also have encountered the same issue.

**Comment by aishat-liasu-bg** [comment]
Hello @kimpoy010, not sure if you resolved your issue.
I got the same error and fixed it by running `npm i emoji-regex --save-dev`

**Comment by aliskhanoff** [comment]
> Hello @kimpoy010, not sure if you resolved your issue. I got the same error and fixed it by running `npm i emoji-regex --save-dev`

WTF it was that simple?! 🤣 I spend an hour installing and reinstalling nodejs
